### ISSUE TITLE
Localization using `robot_localization`

### ISSUE THREAD

**Issue by VAM7686** [RoboJackets/urc-software#15]
## Description
Currently, we do not have any nodes that performs localization. It would be a good start to utilize the robot_localization package to set up a localization node.

Helpful Resources:
- [Configuring `robot_localization`](https://docs.ros.org/en/melodic/api/robot_localization/html/configuring_robot_localization.html)
- Implementation in`igvc_software`
  - [config file](https://github.com/RoboJackets/igvc-software/blob/master/igvc_navigation/config/ekf_localization_node_params.yaml)
  - [launch file](https://github.com/RoboJackets/igvc-software/blob/master/igvc_navigation/launch/localization.launch)

AC: Create an ekf localization node using the `robot_localization` package.

**Comment by s-hliao** [comment]
EKF localization node in progress at fa1701a596b00867c15aa4f623997e4173db7d37.
