### ISSUE TITLE
Implement Live Camera Feed

### ISSUE THREAD

**Issue by a-stickan** [RoboJackets/urc-software#24]
## Description

Finish #42 first!

To operate remotely during the manual control segments of the URC competition, we need to be able to see a live feed of what's around the rover.

## Requirements

 - [Camera is capable of the tasks outlined here](https://urc.marssociety.org/home/requirements-guidelines)
 - Camera can be viewed from the web interface
 - Minimal latency if possible

**Comment by pr05** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ci_pipeline](https://trello.com/c/ctbXuz5i/1-cipipeline)

**Comment by a-stickan** [comment]
Finished with #44
