### ISSUE TITLE
Add magnetometer plugin to robot model

### ISSUE THREAD

**Issue by MKerner3** [RoboJackets/urc-software#33]
## Description
The robot is missing a magnetometer plugin in the robot model. On swervi, this was done with the hector gazebo plugin, which is now available in ros2. However, there is no ros humble branch for the plugin.

This can probably be solved by including the foxy devel branch of the plugin as an external git submodule in the urc repo, and then adding the magnetometer plugin to the robot model from there.
[Link to plugin](https://github.com/tu-darmstadt-ros-pkg/hector_gazebo/blob/foxy-devel/hector_gazebo_plugins/src/gazebo_ros_magnetic.cpp)

**Comment by a-stickan** [comment]
Magnetometer data would only be a marginal improvement to our localization at best. Closing this issue because our effort would be better spent in other areas.
