### ISSUE TITLE
Custom decision node for nav tree

### ISSUE THREAD

**Issue by Kaylia1** [RoboJackets/urc-software#67]
## Description
A decision node that keeps track of the goals in the decision tree. The first 3 times it will travel left in the tree, which is to go to the waypoint, and the other 4 times it will travel right to deal with either stopping at poles or going between them.

## Requirements
 - Traverses tree left 3 times then right 4 times, counting up if child node returns success (1)

**Comment by matthewhannay567** [comment]
@Kaylia1 minor change of plans for this node. We should have this read from a boolean topic to determine if it goes to the left or right child node instead of counting on it's own.

**Comment by a-stickan** [comment]
Stale issue, remake when needed

**Comment by a-stickan** [comment]
Stale issue, remake when needed
