### ISSUE TITLE
LED Node

### ISSUE THREAD

**Issue by s-hliao** [RoboJackets/urc-software#87]
urc_platform needs to have a node that sends LED commands to an LED strip in order to signify teleop, autonomously navigating to goal, or goal reached.

Should take in a msg of type urc_msgs/msg/NavigationState containing a teleop true/false  and a goal_reached true/false. Blue on teleop, red on navigating to goal point, green on goal reached.

**Comment by AR2100** [comment]
What interface will the rover operator use to change the operating mode (autonomous vs teleop)?
